const products = [
  {
    _id: '1',
    name: 'House A',
    image: '/images/A.jpg',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    bed: 1,
    bath: 2,
    lounge: 1,
    dining: 1,
    garage: 2,
  },
  {
    _id: '2',
    name: 'House B',
    image: '/images/B.jpg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    bed: 2,
    bath: 2,
    lounge: 2,
    dining: 1,
    garage: 2,
  },
  {
    _id: '3',
    name: 'House C',
    image: '/images/C.jpg',
    description:
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
    bed: 1,
    bath: 1,
    lounge: 1,
    dining: 1,
    garage: 2,
  },
  {
    _id: '4',
    name: 'House D',
    image: '/images/D.jpg',
    description:
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
    bed: 4,
    bath: 2,
    lounge: 1,
    dining: 1,
    garage: 2,
  },
  {
    _id: '5',
    name: 'House E',
    image: '/images/E.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
    bed: 4,
    bath: 4,
    lounge: 1,
    dining: 1,
    garage: 2,
  },
  {
    _id: '6',
    name: 'House F',
    image: '/images/F.jpg',
    description:
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
    bed: 3,
    bath: 2,
    lounge: 1,
    dining: 1,
    garage: 2,
  },
];

export default products;
